### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by CruelDev69** [JastinXyz/discord-bot-landing-page-web#1]
when you open this website on phone you can't see the nav bar until you scroll down to footer and go back up you should decrease size of navbar

**Comment by JastinXyz** [comment]
wdym? Try to include an image when you report a bug.

On me it's fine, even on my mobile phone it's the same, there's no problem. The hamburger navbar will appear when on mobile.

This is a picture when I tested using [Responsively.app](https://responsively.app/)

![Screenshot from 2022-06-19 05-46-53](https://user-images.githubusercontent.com/73673322/174459346-1dc96e93-5ef2-4fd8-b91d-e59ac5c8f37b.png)

**Comment by CruelDev69** [comment]
See you've to swipe right to see navbar and if you go to footer then come back to top navbar will be in frame otherwise you'll have to swipe right to see it

![Screenshot_20220621-065733](https://user-images.githubusercontent.com/86561855/174700514-b8ada0ad-1d2a-4792-b8bf-a596a50018aa.png)
![Screenshot_20220621-065739](https://user-images.githubusercontent.com/86561855/174700525-37f9fba6-2c59-402c-b8e5-4a2fa99649ac.png)
