### ISSUE TITLE
wide/desktop mode broken

### ISSUE THREAD

**Issue by aurkaxi** [JastinXyz/discord-bot-landing-page-web#3]
![image](https://user-images.githubusercontent.com/72933395/200239638-540842a6-fdb9-4807-9b22-038396c2795c.png)

**Comment by zedeska** [comment]
yeah I have the same issue

**Comment by JastinXyz** [comment]
should be fixed in https://github.com/JastinXyz/discord-bot-landing-page-web/commit/913428649cd4dcc17778306b6709a15930c84f9c
