### ISSUE TITLE
Content is offset on reload

### ISSUE THREAD

**Issue by ackledotdev** [JastinXyz/discord-bot-landing-page-web#4]
After reloading content is offset like so:

Steps to reproduce:
1. Scroll well into the features section
2. Keep reloading

![image](https://github.com/JastinXyz/discord-bot-landing-page-web/assets/111009970/a370670b-c9ed-409a-8587-b9b8bc5e0504)

**Comment by JastinXyz** [comment]
after pushed a new commit (https://github.com/JastinXyz/discord-bot-landing-page-web/commit/913428649cd4dcc17778306b6709a15930c84f9c) after re-check the bug, I think its now solved.
