### ISSUE TITLE
Drop-down menu is in the side of the screen in mobile view and also dekstop

### ISSUE THREAD

**Issue by imnaiyar** [JastinXyz/discord-bot-landing-page-web#5]
The drop down menu is in the side of the screen, at first glance, it isnt visible, but if you scroll right, then you can see it, it generally fixes itself after sometime, same with dekstop mode
![Screenshot_20230815_005710_Chrome](https://github.com/JastinXyz/discord-bot-landing-page-web/assets/137700126/5f7f177a-6afd-4182-9083-f6cf60bbd6c6)

https://github.com/JastinXyz/discord-bot-landing-page-web/assets/137700126/c224785e-54ae-4699-ab60-a25644a6813b

**Comment by JastinXyz** [comment]
Does a bug like that still occur after I pushed the latest commit? Feel free to reopen the issue again if the bug is still exists

https://jastinxyz.github.io/discord-bot-landing-page-web/
